import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css"
import { Navbar } from "../components/NavBar";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css' // Import the CSS
config.autoAddCss = false // Prevent Font Awesome from adding its own CSS


const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const urbanist = localFont({
  src: [{path: "../../public/fonts/Urbanist-BlackItalic.ttf",
    weight: "100 900",
  }],
  variable: "--font-urbanist"
});

export const metadata: Metadata = {
  title: "Devstrike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist} antialiased bg-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
